### PR TITLE
feat: include neutral condition

### LINKED ISSUE #420: Allow neutral status
I'm using this in combination with Azure Devops checks and they report a neutral state back when they are skipped due to path exclusion. 

It would be nice if the 'neutral' conclusion state would be marked as success. 

There are two ways to do this:
1. add 'neutral' to this [line](https://github.com/poseidon/wait-for-status-checks/blob/main/src/poll.ts#L159C5-L159C72)  
2. make the acceptable conclusions configurable with a default of 'skipped' and 'success'

Happy to contribute with a PR.

### PR DESCRIPTION
**Pull request by lazytesting**
resolves  #420

### CODE REVIEW

**Comment by dghubble** [comment]
Looks like it needs a rebase and npm run all

**Comment by lazytesting** [comment]
> Looks like it needs a rebase and npm run all

done that, let me know if you need anything else

**Comment by dghubble** [comment]
This doesn't look right? its got a conflict and there should just be your one or two commits

**Comment by lazytesting** [comment]
sorry this got messy, let me recreate this change

**Pull request closed without merging**
